name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request_target:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: ./
        with:
          ms-teams-webhook-url: ${{ secrets.TEST_WEBHOOK_URL }}
          github-token: ${{ github.token }}
          github-repo: ${{ github.repository }}
          github-tag: v1.0.0
          anonymize: false
